### PR TITLE
Fix colors for real

### PR DESCRIPTION
**Pull request by euri10**
Adds missing flags for use_colors, sorry about the oversight

### CODE REVIEW

**Comment by euri10** [comment]
I honestly have no clue why this fails on 3.8 for one test, works locally ...

**Comment by euri10** [comment]
on a side note, the cli part is not tested, 
somehting very simple like that would have caught it, on top of that the `--help` output could be reused in the docs for less DRY, just an idea if you want another shot at it in a new PR let me know


```
Index: tests/test_cli.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tests/test_cli.py	(date 1576048446757)
+++ tests/test_cli.py	(date 1576048446757)
@@ -0,0 +1,92 @@
+from click.testing import CliRunner
+
+from uvicorn.main import main
+
+HELP_OUTPUT = """Usage: main [OPTIONS] APP
+
+Options:
+  --host TEXT                     Bind socket to this host.  [default:
+                                  127.0.0.1]
+  --port INTEGER                  Bind socket to this port.  [default: 8000]
+  --uds TEXT                      Bind to a UNIX domain socket.
+  --fd INTEGER                    Bind to socket from this file descriptor.
+  --reload                        Enable auto-reload.
+  --reload-dir TEXT               Set reload directories explicitly, instead of
+                                  using the current working directory.
+  --workers INTEGER               Number of worker processes. Defaults to the
+                                  $WEB_CONCURRENCY environment variable if
+                                  available. Not valid with --reload.
+  --loop [auto|asyncio|uvloop|iocp]
+                                  Event loop implementation.  [default: auto]
+  --http [auto|h11|httptools]     HTTP protocol implementation.  [default: auto]
+  --ws [auto|none|websockets|wsproto]
+                                  WebSocket protocol implementation.  [default:
+                                  auto]
+  --lifespan [auto|on|off]        Lifespan implementation.  [default: auto]
+  --interface [auto|asgi3|asgi2|wsgi]
+                                  Select ASGI3, ASGI2, or WSGI as the
+                                  application interface.  [default: auto]
+  --env-file PATH                 Environment configuration file.
+  --log-config PATH               Logging configuration file.
+  --log-level [critical|error|warning|info|debug|trace]
+                                  Log level. [default: info]
+  --access-log / --no-access-log  Enable/Disable access log.
+  --use-colors / --no-use-colors  Enable/Disable colorized logging.
+  --proxy-headers / --no-proxy-headers
+                                  Enable/Disable X-Forwarded-Proto, X-Forwarded-
+                                  For, X-Forwarded-Port to populate remote
+                                  address info.
+  --forwarded-allow-ips TEXT      Comma seperated list of IPs to trust with
+                                  proxy headers. Defaults to the
+                                  $FORWARDED_ALLOW_IPS environment variable if
+                                  available, or '127.0.0.1'.
+  --root-path TEXT                Set the ASGI 'root_path' for applications
+                                  submounted below a given URL path.
+  --limit-concurrency INTEGER     Maximum number of concurrent connections or
+                                  tasks to allow, before issuing HTTP 503
+                                  responses.
+  --limit-max-requests INTEGER    Maximum number of requests to service before
+                                  terminating the process.
+  --timeout-keep-alive INTEGER    Close Keep-Alive connections if no new data is
+                                  received within this timeout.  [default: 5]
+  --ssl-keyfile TEXT              SSL key file
+  --ssl-certfile TEXT             SSL certificate file
+  --ssl-version INTEGER           SSL version to use (see stdlib ssl module's)
+                                  [default: 2]
+  --ssl-cert-reqs INTEGER         Whether client certificate is required (see
+                                  stdlib ssl module's)  [default: 0]
+  --ssl-ca-certs TEXT             CA certificates file
+  --ssl-ciphers TEXT              Ciphers to use (see stdlib ssl module's)
+                                  [default: TLSv1]
+  --header TEXT                   Specify custom default HTTP response headers
+                                  as a Name:Value pair
+  --help                          Show this message and exit.
+"""
+
+
+ERROR_APP = """ERROR:    Error loading ASGI app. Import string "App" must be in format "<module>:<attribute>".
+"""
+
+
+class App:
+    def __init__(self, scope):
+        if scope["type"] != "http":
+            raise Exception()
+
+    async def __call__(self, receive, send):
+        await send({"type": "http.response.start", "status": 204, "headers": []})
+        await send({"type": "http.response.body", "body": b"", "more_body": False})
+
+
+def test_help():
+    runner = CliRunner()
+    result = runner.invoke(main, ["--help"])
+    assert result.exit_code == 0
+    assert result.output == HELP_OUTPUT
+
+
+def test_main_command():
+    runner = CliRunner()
+    result = runner.invoke(main, ["App"])
+    assert result.exit_code == 1
+    assert result.output == ERROR_APP
```

**Comment by euri10** [comment]
@tomchristie the failing test is a false positive imho, both previous builds are failing here, once in python 3.7 the other time on 3.8, which makes no sense at all since  both succeed locally and in my fork's travis, 
I'd fix the test adding a small small delay after the touch 

https://travis-ci.org/euri10/uvicorn/builds/623570969?utm_medium=notification&utm_source=github_status

**Comment by wapiflapi** [comment]
Can confirm the failed test is a false positive, I worked on the corresponding code in https://github.com/encode/uvicorn/pull/519 and I had to fix the test.

**Comment by lovelydinosaur** [comment]
>  I'd fix the test adding a small small delay after the touch

Yeah seems right. It'd be nice if we could do something more graceful, but that'd do.
I've restarted that test here, and it's passed now.
Would you be up for subitting a PR for that?

**Comment by wapiflapi** [comment]
> Would you be up for subitting a PR for that?

Already fixed in #519, feel free to take only the test if you want it separate from the rest of the PR ;-)

**Comment by euri10** [comment]
happy to do it but I don't know what etiquette is and dont want to "steal" @wapiflapi work so will do if he's ok of course

**Pull request merged**
