### PR TITLE
Support backlog configuration

### PR DESCRIPTION
**Pull request by aviramha**
Addresses #544 
Adds a new field for configuration - backlog.

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Seems reasonable. We should also bump up the defult for this value up to `2048`, to match `gunicorn`.

**Comment by aviramha** [comment]
> Seems reasonable. We should also bump up the defult for this value up to `2048`, to match `gunicorn`.

Done!

**Comment by euri10** [comment]
An addition to the docs would be cool as well

**Comment by aviramha** [comment]
> An addition to the docs would be cool as well

Done :)

**Comment by lovelydinosaur** [comment]
Thanks!

**Comment by aviramha** [comment]
You're welcome, my pleasure supporting this wonderful project :)

**Pull request merged**
