### PR TITLE
Reloader yields PermissionError on windows after a syntax error

### PR DESCRIPTION
**Pull request by euri10**
Attempt at solving #684 
It replaces  #686 which seems weaker
see https://docs.python.org/3/library/os.html#os.kill

### CODE REVIEW

**Comment by abersheeran** [comment]
Great solution, hope to merge as soon as possible~

**Comment by euri10** [comment]
> Great solution, hope to merge as soon as possible~

would you test it please ? I have no windows at hand unfortunately, and I would be interested in knowing if there are process left after a reload or if the signal kills them cleanly ?
would be amazing if someone could take a look at that

**Comment by abersheeran** [comment]
Unfortunately, after trying it on Windows 10, I found that the restart can be successful the first time, but I cannot restart the second time. It got stuck there and there was no response.

There should be some questions that I don't know. I will check the Windows signal again.

**Comment by abersheeran** [comment]
I found it. `TerminateProcess` should be used on Windows.

**Comment by euri10** [comment]
https://maruel.ca/post/python_windows_signal/

**Comment by abersheeran** [comment]
Maybe you can take a look at https://github.com/encode/uvicorn/pull/744? 

By the way, it's early morning in China, and I need to sleep. Maybe the next reply will be a long time later. good night.

**Comment by euri10** [comment]
not the correct solution it seems

**Pull request closed without merging**
