### PR TITLE
Add reload test base class

### PR DESCRIPTION
**Pull request by Roang-zero1**
As requested in https://github.com/encode/uvicorn/pull/820#pullrequestreview-512652180 I've separated out the reloader test class refactor.

New Features:
* Use custom test class for reloader test setup/teardown
* Use tmpdir.as_cwd from pytest to switch context

### CODE REVIEW

**Comment by euri10** [comment]
LGTM but I'd go one step further, the class could be parametrized and all the individual tests put in the class.
something like https://github.com/encode/uvicorn/compare/master...euri10:Roang-zero1-feature/reload-test-class

what you think ?

**Comment by Roang-zero1** [comment]
LGTM.
I didn't know about this feature.
Will you also modify the other pull request for this test structure?

**Comment by euri10** [comment]
simplest would be to merge this test refactor and then you'd have to rebase
?

**Comment by Roang-zero1** [comment]
Let's do that

**Comment by euri10** [comment]
I let you take it from my fork's branch @Roang-zero1 so that you keep this PR ?

**Comment by Roang-zero1** [comment]
Thanks! I've merged the changes.

**Review by euri10 — APPROVED** [review]

**Comment by euri10** [comment]
thanks a lot @Roang-zero1 :)

**Pull request merged**
