### PR TITLE
Version 0.11.4

### PR DESCRIPTION
**Pull request by lovelydinosaur**
* Use `watchgod`, if installed, for watching code changes.
* Reload application when any files in watched directories change, not just `.py` files.

Requires #653 first, so that we've got GitHub actions setup to handle publishing new versions.

I've drafted a release, ready to publish once this has been merged... https://github.com/encode/uvicorn/releases/tag/untagged-d09964eb56f9304a4a91

### CODE REVIEW

**Review by yeraydiazdiaz — APPROVED** [review]

**Comment by rafalp** [comment]
@tomchristie  most recent version's header in `changelog.md` still says `Unreleased` instead of 0.11.4.

**Review by rafalp — APPROVED** [review]

**Comment by lovelydinosaur** [comment]
Okey doke, let's give the "Publish" GitHub Action a whirl then, see if I've missed something or not.

**Comment by lovelydinosaur** [comment]
Published this release now... https://github.com/encode/uvicorn/releases/tag/0.11.4

Which has kicked off this... https://github.com/encode/uvicorn/actions/runs/90275150

**Comment by lovelydinosaur** [comment]
Yas! 🎉

Screenshot 2020-04-28 at 16 23 37

*Updated on PyPI*

Screenshot 2020-04-28 at 16 24 00

*Updated docs*

**Pull request merged**
