### PR TITLE
Remove `DebugMiddleware`

### PR DESCRIPTION
**Pull request by edmorley**
Since it's unused and untested as of #1640.

### CODE REVIEW

**Comment by Kludex** [comment]
Would you mind bumping a bit the coverage `fail-under` value? It should be enough the number that was on that PR before 👀 🙏

**Comment by edmorley** [comment]
Yeah I was going to wait until the runs have finished to see what value I can use, since I suspect the exact coverage percentage might still be slightly different (🥔s! 😄).

**Review by Kludex — APPROVED** [review]

**Comment by edmorley** [comment]
I checked all runs and lowered the coverage percentage to `97.71`, however on the next test run the `Python 3.7 macos-latest` job then resulted in a lower coverage percentage than it had before? Is the coverage percentage flaky?

This run said `97.69`:
https://github.com/encode/uvicorn/actions/runs/3204878159/jobs/5236700388#step:8:25

Whereas the prior one said `97.71`:
https://github.com/encode/uvicorn/actions/runs/3204794323/jobs/5236511876#step:8:25

**Comment by Kludex** [comment]
> Is the coverage percentage flaky?

There's a chance that some test is flaky resulting in the coverage being as well... 👀 

Something around files, and filenames on MacOS.

**Comment by edmorley** [comment]
Should I return the coverage percentage back to what it was before this PR, or would you like to rerun the CI jobs to see if they pass next time? (I don't have permissions to retrigger CI)

**Comment by Kludex** [comment]
Return the coverage, please 🙏

**Comment by edmorley** [comment]
Done :-)

**Comment by Kludex** [comment]
Thank you @edmorley 🎉 

Btw, how did you find about this? 👀

**Comment by edmorley** [comment]
I just happened to be looking at recent PRs and was wondering what the DebugMiddleware did, and so was looking for the file removal diff in the PR to see its original contents, only to see there was no such removal in that PR :-)

**Comment by Kludex** [comment]
Cool. Thank you! 🙏

**Pull request merged**
