### PR TITLE
Fix: don't error if WS still connected during shutdown

### LINKED ISSUE #326: Server shutdown errors if WebSocket connection is still open
If I stop the server while a WS connection is still open, I get different issues depending on the ws protocol.

Test app:
```python
import asyncio

from starlette.websockets import WebSocket


class App:
    def __init__(self, scope):
        assert scope['type'] == 'websocket'
        self.scope = scope

    async def __call__(self, receive, send):
        websocket = WebSocket(self.scope, receive=receive, send=send)

        await websocket.accept()
        while True:
            await websocket.send_text('Hello, world!')
            await asyncio.sleep(1)
        await websocket.close()
```

Test client:
```python
import asyncio

import websockets
import websockets.exceptions
import websockets.protocol


async def recv(websocket):
    while websocket.state == websockets.protocol.State.OPEN:
        try:
            message = await websocket.recv()
        except websockets.exceptions.ConnectionClosed as exc:
            print('ConnectionClosed with code:', exc.code)
        else:
            print('Received message:', message)


async def main(uri):
    async with websockets.connect(uri) as websocket:
        try:
            await recv(websocket)
        finally:
            await websocket.close()


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main("ws://127.0.0.1:8000"))
```

With `wsproto`
```
(.venv) > uvicorn app:App --ws wsproto
INFO: Started server process [25393]
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: ('127.0.0.1', 51014) - "WebSocket /" [accepted]
^CINFO: Shutting down
Traceback (most recent call last):
  File "/home/jose/workspace/uvicorn_test/.venv/bin/uvicorn", line 9, in <module>
    load_entry_point('uvicorn==0.5.2', 'console_scripts', 'uvicorn')()
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/uvicorn/main.py", line 245, in main
    run(**kwargs)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/uvicorn/main.py", line 266, in run
    server.run()
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/uvicorn/main.py", line 293, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/uvicorn/main.py", line 310, in serve
    await self.shutdown(shutdown_servers=shutdown_servers)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/uvicorn/main.py", line 406, in shutdown
    connection.shutdown()
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 114, in shutdown
    output = self.conn.send(wsproto.events.CloseConnection(code=code))
NameError: name 'code' is not defined
```

With `websockets`:

```
(.venv) > uvicorn app:App --ws websockets
INFO: Started server process [25139]
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: ('127.0.0.1', 51004) - "WebSocket /" [accepted]
^CINFO: Shutting down
INFO: Waiting for background tasks to complete. (CTRL+C to force quit)
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/usr/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 147, in run_asgi
    result = await asgi(self.asgi_receive, self.asgi_send)
  File "./app.py", line 16, in __call__
    await websocket.send_text('Hello, world!')
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/starlette/websockets.py", line 107, in send_text
    await self.send({"type": "websocket.send", "text": data})
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/starlette/websockets.py", line 68, in send
    await self._send(message)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 205, in asgi_send
    await self.send(data)
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/websockets/protocol.py", line 462, in send
    yield from self.ensure_open()
  File "/home/jose/workspace/uvicorn_test/.venv/lib/python3.6/site-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
INFO: Finished server process [25139]
```

### PR DESCRIPTION
**Pull request by JoseKilo**
Close: #326 

I started to work on the issues reported on #326, but I ended up making many changes.
Happy to discuss / split any changes.

To explain the original issues:
- using wsproto: the variable `code` is not defined in the `shutdown` method (and not covered by tests).
- using websockets: the ws implementation keeps trying to send messages if requested by the App even when the connection is already closed.

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Looks like there's maybe some behavioral differences on windows here? https://travis-ci.org/encode/uvicorn/jobs/511056658

**Comment by JoseKilo** [comment]
Indeed. It could also be related to the python version: 3.7.2 on windows VS 3.7.0a4+ on linux.
I will try to reproduce it locally using 3.7.2 (I've tried with 3.6.7 and 3.7.0b5).

**Comment by JoseKilo** [comment]
Tests passing on windows now. It was just a timeout kicking in earlier than expected.

**Comment by lovelydinosaur** [comment]
Okay good work.
Whole lot to review here 👀

**Comment by lovelydinosaur** [comment]
If you are able to put the time into making a smaller set of incremental PRs that'd certainly be helpful in getting this work in. Bit difficult to do a properly thorough review as it stands.

**Comment by last-partizan** [comment]
Any news on this?

**Comment by JoseKilo** [comment]
I will try to split this PR into smaller bits. #378 is the first one.

**Comment by euri10** [comment]
Obsolete with master, see https://github.com/encode/uvicorn/issues/326#issuecomment-743741982

**Pull request closed without merging**
