### PR TITLE
add types to wsgi module

### PR DESCRIPTION
**Pull request by jkklapp**
Part of #998

### CODE REVIEW

**Comment by Kludex** [comment]
@jkklapp Thanks for the PR! :tada: 

We're now using `asgiref.typing` instead of `_types.py` module. Do you mind updating this PR using `asgiref.typing` instead?

**Comment by Vibhu-Agarwal** [comment]
@Kludex May I extend this PR?
(Commits by @jkklapp will remain)

**Comment by Kludex** [comment]
@Vibhu-Agarwal You're more than welcome.

**Comment by Kludex** [comment]
Thanks for the PR @jkklapp ! :)
I guess @Vibhu-Agarwal will take the lead now, and as he said, your contributions will not be erased! :tada: 

Thanks for volunteering here @Vibhu-Agarwal :smile:

**Pull request closed without merging**
