### PR TITLE
Added python 3.9 support

### PR DESCRIPTION
**Pull request by euri10**

### CODE REVIEW

**Review by cdeler — APPROVED** [review]
Approved

**Comment by euri10** [comment]
> Approved

thanks @cdeler !

**Comment by qeternity** [comment]
How was this added before uvloop had 3.9 support?

**Comment by HarrySky** [comment]
@qeternity `uvloop` is an optional dependency since 0.12.0, so I don't see a problem here.

**Comment by qeternity** [comment]
@HarrySky fair enough, but from the test pipeline it seems the 3.9 pipeline is installing uvloop and passing...I can attest that uvicorn + uvloop in 3.9 does not work.

**Comment by euri10** [comment]
> @HarrySky fair enough, but from the test pipeline it seems the 3.9 pipeline is installing uvloop and passing...I can attest that uvicorn + uvloop in 3.9 does not work.

does not work is not helpful, raise a real issue following the template if you feel something is not working the way you think it should.

a small test here and I run a Starlette app on 3.9 fine.

```
❯ pip install starlette uvicorn
Collecting starlette
  Downloading starlette-0.14.1-py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 3.7 MB/s 
Collecting uvicorn
  Using cached uvicorn-0.12.2-py3-none-any.whl (45 kB)
Collecting h11>=0.8
  Using cached h11-0.11.0-py2.py3-none-any.whl (54 kB)
Collecting click==7.*
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Installing collected packages: starlette, h11, click, uvicorn
Successfully installed click-7.1.2 h11-0.11.0 starlette-0.14.1 uvicorn-0.12.2
❯ 
❯ 
❯ which python
/home/lotso/PycharmProjects/uvicornOn39/venv/bin/python
❯ uvicorn --version
Running uvicorn 0.12.2 with CPython 3.9.0 on Linux
❯ uvicorn app:app
INFO:     Started server process [25599]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:50872 - "GET / HTTP/1.1" 200 OK
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [25599]
  ~/PycharmProjects/uvicornOn39 ❯       
```

**Comment by qeternity** [comment]
@euri10 Yes agreed, but that's because it's not a uvicorn issue, it's a uvloop issue. If you bothered to think about my comment before leaping to your own defense, I'm not suggesting anything isn't working as expected. I know exactly why 3.9 is broken, and it's not uvicorn. No sense in filing an issue for something in the wrong repo especially when it's resolved in the correct repo.

My observation is a different one anyway: given that uvloop 0.14.0 does not work in 3.9, it's concerning that tests were passing here. But there's nothing to file yet, because before you jumped down my throat, I was merely trying to prompt a discussion for further investigation.

**Comment by euri10** [comment]
dont feel attacked where I was just trying to make you post something more explicit than:

> I can attest that uvicorn + uvloop in 3.9 does not work.

It's not an actionable comment for us. What does not work ?

> My observation is a different one anyway: given that uvloop 0.14.0 does not work in 3.9, it's concerning that tests were passing here. But there's nothing to file yet, because before you jumped down my throat, I was merely trying to prompt a discussion for further investigation.

this I dont know for sure, last time I check uvloop was ok with 3.9 except for a new method we dont use, that may explain the tests ok here.
Feel free to raise an actionable issue, explicit is better than implicit ;)

**Pull request merged**
