### PR TITLE
Bump uvloop to v0.18.0

### PR DESCRIPTION
**Pull request by Ale-Cas**
# Summary

This PR bumps uvloop to v0.18.0 to try and address the mypy error in feat/support-3.12.
Related:
https://github.com/encode/uvicorn/pull/2129#issuecomment-1763485380

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by Kludex** [comment]
That PR is already using the latest uvloop, that's exactly why it's failing.

**Comment by Ale-Cas** [comment]
You're right I thought it was using 0.17 but I double-checked the run and it's already 0.18, I'm trying to understand what would make mypy see EventLoopPolicy since it's in the uvloop __init__ but I guess that's not related to uvicorn so I'll close this, sorry for the spam 🙏🏻

**Comment by Kludex** [comment]
np. Thanks for closing it. 👍

**Comment by graingert** [comment]
@Ale-Cas they added an `__init__.pyi` with most of the members removed this hides EventLoopPolicy from mypy. The issue is fixed upstream pending a release this weekend: https://github.com/MagicStack/uvloop/issues/575#issuecomment-1771305350

**Comment by Ale-Cas** [comment]
Great! thank you both!
I was thinking something like this workaround / temp solution would make mypy happy:
```python
def uvloop_setup(use_subprocess: bool = False) -> None:
    if hasattr(uvloop, "EventLoopPolicy"):
        asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```
and maybe not related but what's the reason for the unused use_subprocess variable there? is it just for compatibility with the loop_setup from asyncio?

**Pull request closed without merging**
