### PR TITLE
Delete js folder and remove extra_javascript

### PR DESCRIPTION
**Pull request by MhmoudGit**
# Summary
I found an issue about the chat button not working on website and there was a suggestion to remove the docs/js files.
So I deleted the extra_javascript in mkdocs.yaml and the js folder altogether.

# Impact
This will remove the "Open Chat" button from the docs website.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by zanieb** [comment]
@MhmoudGit thanks for contributing. Which issue are you referring to?

**Comment by MhmoudGit** [comment]
Hi @zanieb, I did the same PR regarding issue #2303 on `starlette` and @Kludex asked if I can do the same PR in `uvicorn` and `httpx` so I did this one and on `httpx` as well.

**Comment by Kludex** [comment]
Can we link the other PRs here? :eyes:

**Comment by MhmoudGit** [comment]
The one on `httpx` was approved, merged and closed so only this and `starlette` are opened for now. 
Do you mean I should put a link here? or that question wasn't for me? :sweat_smile:

**Comment by Kludex** [comment]
'-'
- https://github.com/encode/httpx/pull/2899
- https://github.com/encode/starlette/issues/2303

**Review by Kludex — APPROVED** [review]

**Pull request merged**
