### PR TITLE
Add trusted networks

### PR DESCRIPTION
**Pull request by b4stien**
Deploying FastAPI in AWS behind an AWS Load Balancer I hit a roadblack to trust the proxy (the Load Balancer): I know its network but not its IPs. Using `ProxyHeadersMiddleware` as it is, I'd have to know those IPs beforehand to trust them.

Would you be willing to consider a slight modification to `ProxyHeadersMiddleware` to accept `trusted_networks` in addition to `trusted_hosts`?

Attached is some working code of how it would work.

# Checklist

- [x]  I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x]  I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ]  I've updated the documentation accordingly.

_PS: [I've opened a discussion](https://github.com/encode/uvicorn/discussions/2388), you can close this PR in the meantime if needed, it'll still reference some code ideas._

### CODE REVIEW

**Comment by Kludex** [comment]
The current implementation works for trusted networks now. :)

**Comment by b4stien** [comment]
Oh ok, wonderful! Could you provide a ref of the relevant commits implementing it? Or the docs for the feature?

**Comment by b4stien** [comment]
This is https://github.com/encode/uvicorn/pull/2468 and https://github.com/encode/uvicorn/pull/2231, right?

**Comment by Kludex** [comment]
> This is #2468 and #2231, right?

Yes.

**Comment by Kludex** [comment]
> Oh ok, wonderful! Could you provide a ref of the relevant commits implementing it? Or the docs for the feature?

https://www.uvicorn.org/deployment/#proxies-and-forwarded-headers

**Pull request closed without merging**
