### PR TITLE
Add a logger config file example and how to use it

### LINKED ISSUE #491: Add example of logging config file
In the doc, there is the description of `--log-config <path>` for the configuration of a config file. I think an example of config file could be really awesome for the new comers.

> [!Important]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/491">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/491/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by bijela-gora**
## Summary

Hello,

Thank you for paying attention to this.

I've added an example how to use logger config file and how it can look like. The changes should resolve #491

Thank you in advance for a review.

## Checklist

- [x] I've updated the documentation
- [x] I've checked how changes to the doc page looks like, by using the `scripts/docs serve` command
- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)

## New section screenshot

image

### CODE REVIEW

**Comment by bijela-gora** [comment]
@Kludex @tomchristie hi,

I'd appreciate it if you could review this PR. Thank you in advance.

Sorry, for mentioning you. Details and a screenshot in the first PR comment.

**Review by lovelydinosaur — APPROVED** [review]
Looks really neat. ☺️

**Comment by bijela-gora** [comment]
Thank you!

What else should be done to squash merge this? I don't have a merge button.

**Comment by Kludex** [comment]
I don't think we should be recommending any third-party package here.

I also think we need a whole section about logging.

**Comment by Kludex** [comment]
- Related: https://github.com/encode/uvicorn/pull/2031/

**Comment by bijela-gora** [comment]
@Kludex

Hello, thank you for the review.

I decided to take structured login as an example because it's widely adopted, it's useful and valuable. I fully understand and accept your desire not to recommend any third-party packages, even though I don't have the same experience in open source as you. For me it will be even more interesting to use Python native abilities to implement structured logging.

During preparation of the section about `--log-config` parameter, I felt tendency to write a lot more then is written, to show the whole example. But then I realized that it looks like a tutorial about logging, and not a short example. So, I stopped myself. This PR was created just to close the #491 issue. 

If you'll allow me, I can only speak for myself, I was looking for exactly this kind of section. About structural logging. It is now a de-facto industry standard. I agree that there is still a lot to be said about logging. But I also believe that even such a small improvement will be useful.

So, before I go on, I want to ask you if you will accept my PR if I remove the third-party package recommendation?

By the way, I checked the [source code of python-json-logger](https://github.com/madzak/python-json-logger/blob/master/src/pythonjsonlogger/jsonlogger.py) and it looks small and quite simple, means easily auditable.

**Pull request closed without merging**
