### PR TITLE
Deprecate WSGIMiddleware

### PR DESCRIPTION
**Pull request by abersheeran**
Related links: https://github.com/encode/uvicorn/pull/1049#issuecomment-870520562

### CODE REVIEW

**Comment by abersheeran** [comment]
It seems that using DeprecationWarning directly will cause the test to fail, how can I fix it?

**Comment by euri10** [comment]
add it in setup.cfg ?

```
    ignore:The built-in `WSGIMiddleware` will be deprecated in future versions, please use `a2wsgi.WSGIMiddleware` instead.:DeprecationWarning
```

**Review by Kludex — COMMENTED** [review]
Maybe we should deprecate the module instead?

Like, we are not strict when it comes to private/public objects, so I guess the middleware and `build_environ`/`WSGIResponder` are in the same privacy level. Does it make sense?

**Comment by abersheeran** [comment]
> Maybe we should deprecate the module instead?
> 
> Like, we are not strict when it comes to private/public objects, so I guess the middleware and `build_environ`/`WSGIResponder` are in the same privacy level. Does it make sense?

Agree with your ideas. But I am not sure how to do it...I have no experience in this area. Is there a module that has already done this for me?

**Comment by Kludex** [comment]
I guess like this: https://github.com/encode/uvicorn/pull/1205/files#diff-7c8a9d71c98f0ed83c32a88a1b7e777ef85776c98869045d24c74e3f7714494a

Yeah, we never deprecated modules on uvicorn before, this would be the first time. We have done it for starlette: https://github.com/encode/starlette/blob/8a3e41a5442239bb2da5f2df6cfaaf4683e49f96/starlette/graphql.py#L12-L17

**Comment by Kludex** [comment]
What's the plan with `--interface wsgi`?

The idea is to import the middleware from `a2wsgi`?

**Comment by abersheeran** [comment]
> What's the plan with `--interface wsgi`?
> 
> The idea is to import the middleware from `a2wsgi`?

Do I need to submit it in this PR? I took a quick look at the code and it shouldn't be difficult to implement.

**Comment by Kludex** [comment]
> > What's the plan with `--interface wsgi`?
> > 
> > The idea is to import the middleware from `a2wsgi`?
> 
> Do I need to submit it in this PR? I took a quick look at the code and it shouldn't be difficult to implement.

No, I just want to confirm the best steps.

**Comment by Kludex** [comment]
@abersheeran What's our plan for it? :thinking:

**Comment by abersheeran** [comment]
> @abersheeran What's our plan for it? 🤔

I don't quite understand what you mean. 👀

**Comment by euri10** [comment]
let's favor https://github.com/encode/uvicorn/pull/1303

**Pull request closed without merging**
