### PR TITLE
📦️ Add PEP440 compliant version of click

### LINKED ISSUE #1098: PackageInfo: Invalid constraint (click (>=7.*)) found in uvicorn-0.14.0 dependencies, skipping
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When adding uvicorn package with poetry the following warning is raised:

    PackageInfo: Invalid constraint (click (>=7.*)) found in uvicorn-0.14.0 dependencies, skipping

because the constraint `>=7.*` violates PEP440 syntax. It should either be `>=7.0` or `=7.*`.

Because of this, the `click` dependency is not installed and uvicorn may not work.

### To reproduce

Just execute `poetry add uvicorn` in any environment.

### Expected behavior

To install `uvicorn` correctly together with all its dependencies.

### Actual behavior

The `click` dependency is not installed and uvicorn may not work.

### PR DESCRIPTION
**Pull request by Kludex**
Fixes #1098.

### CODE REVIEW

**Comment by euri10** [comment]
lint fails on

 ```
uvicorn/middleware/proxy_headers.py:13: error: Module "asgiref.typing" has no attribute "WebsocketScope"; maybe "WebSocketScope"?  [attr-defined]
```

**Comment by Kludex** [comment]
That's so funny. :sweat_smile: I was the one who changed that interface on `asgiref`: https://github.com/django/asgiref/pull/272

It's not from this PR :)
master branch is broken. I'm going to fix it.

**Review by euri10 — APPROVED** [review]

**Review by euri10 — CHANGES_REQUESTED** [review]
ci is failing not sure why

edit: also not sure why I' doing thingss twice, sorry for that

**Review by euri10 — APPROVED** [review]

**Comment by euri10** [comment]
thanks @Kludex

**Pull request merged**
