### PR TITLE
Improve coverage on Proxyheaders Middleware

### PR DESCRIPTION
**Pull request by iudeen**

### CODE REVIEW

**Comment by Kludex** [comment]
Please read https://github.com/encode/uvicorn/pull/1349.

**Comment by iudeen** [comment]
Yes, it'd be a never occurring misconfiguration. What do I do now? Not add a test for this scenario? Or raise exception in the code?

**Comment by Kludex** [comment]
> Yes, it'd be a never occurring misconfiguration. What do I do now? Not add a test for this scenario? Or raise exception in the code?

I'm inclined to say "yes", but I have to reread some stuff to be sure... :eyes:

**Comment by iudeen** [comment]
I am inclined towards raising ~~`InputError` or~~ `RuntimeError`...any suggestions?

**Comment by Kludex** [comment]
- Closing this in favor of #1611

**Pull request closed without merging**
