### PR TITLE
differentiate %2f and / in url path

### PR DESCRIPTION
**Pull request by link89**
# Summary
differentiate  %2F and / when unquote path

https://github.com/encode/uvicorn/discussions/2423

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by Kludex** [comment]
Why urllib doesn't have this logic then?

**Comment by link89** [comment]
I guess that's because how to encode/decode path is not part of URI standard but a W3C recommendation. 

https://www.w3.org/Addressing/URL/4_URI_Recommentations.html

I try to find a method to allow me to ignore specific %xx, for example `unquote(path, ignore=('%2f', '%2F'))` but with no luck.

I have try another asgi engine `hypercorn` which do follow the URI recommentations and there are quite a lot of related issue about this.

**Comment by Kludex** [comment]
> I have try another asgi engine hypercorn which do follow the URI recommentations and there are quite a lot of related issue about this.

Can you point me out to those issues?

**Comment by link89** [comment]
Sure, how about discuss in https://github.com/encode/uvicorn/discussions/2423

**Comment by Kludex** [comment]
Given the comment on https://github.com/encode/uvicorn/discussions/2423#discussioncomment-10323966, I'll be closing this PR.

**Pull request closed without merging**
