### PR TITLE
Fix windows 1022 error using multiple workers

### LINKED ISSUE #514: [BUG] WinError 10022 when run on Windows with workers > 1
The error observed on Windows 10 with Python-3.6-amd64, Python-3.7-amd64, Python-3.8-amd64.
Sample app:
```python
async def app(scope, receive, send):
    assert scope['type'] == 'http'
    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ]
    })
    await send({
        'type': 'http.response.body',
        'body': b'Uvicorn is the best!',
    })
```

OK when workers=1:
```
(venv) C:\Users\vasiliy.pankov\Projects\uvicorn-lab>uvicorn server:app
[32mINFO[0m:     Started server process [[36m17728[0m]
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     ASGI 'lifespan' protocol appears unsupported.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Finished server process [[36m17728[0m]
```

WinError 10022 When workers > 1
```
(venv) C:\Users\vasiliy.pankov\Projects\uvicorn-lab>uvicorn --workers 2 server:app
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     Started parent process [[36m[1m13020[0m]
[32mINFO[0m:     Started server process [[36m6888[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     ASGI 'lifespan' protocol appears unsupported.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Started server process [[36m19460[0m]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Python\Python38\lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
  File "C:\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\vasiliy.pankov\projects\uvicorn-lab\venv\lib\site-packages\uvicorn\subprocess.py", line 73, in subprocess_started
    target(sockets=sockets)
  File "c:\users\vasiliy.pankov\projects\uvicorn-lab\venv\lib\site-packages\uvicorn\main.py", line 341, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "c:\users\vasiliy.pankov\projects\uvicorn-lab\venv\lib\site-packages\uvicorn\main.py", line 358, in serve
    await self.startup(sockets=sockets)
  File "c:\users\vasiliy.pankov\projects\uvicorn-lab\venv\lib\site-packages\uvicorn\main.py", line 386, in startup
    server = await loop.create_server(
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 1469, in create_server
    server._start_serving()
  File "C:\Python\Python38\lib\asyncio\base_events.py", line 309, in _start_serving
    sock.listen(self._backlog)
OSError: [WinError 10022] An invalid argument was supplied
```

### LINKED ISSUE #683: Invalid argument was supplied error on windows
There seems to be an issue when I increase the worker process count greater than 1.
**command** -> `uvicorn --port 9000 --workers 2 MyProject.asgi:application`
**error log** ->
```
INFO:     Uvicorn running on http://127.0.0.1:9000 (Press CTRL+C to quit)
INFO:     Started parent process [17696]
INFO:     Started server process [20428]
INFO:     Started server process [15476]
INFO:     Waiting for application startup.
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Application startup complete.
Process SpawnProcess-2:
Traceback (most recent call last):
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\multiprocessing\process.py", line 297, in _bootstrap    
    self.run()
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "t:\my projects\scholify-web\env\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "t:\my projects\scholify-web\env\lib\site-packages\uvicorn\main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "t:\my projects\scholify-web\env\lib\site-packages\uvicorn\main.py", line 399, in serve
    await self.startup(sockets=sockets)
  File "t:\my projects\scholify-web\env\lib\site-packages\uvicorn\main.py", line 433, in startup
    create_protocol, sock=sock, ssl=config.ssl, backlog=config.backlog
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\asyncio\base_events.py", line 1393, in create_server    
    server._start_serving()
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\asyncio\base_events.py", line 282, in _start_serving    
    sock.listen(self._backlog)
OSError: [WinError 10022] An invalid argument was supplied
```

### PR DESCRIPTION
**Pull request by euri10**
Fixes #514 shamelessly inspired by hypercorn
Fixes #683 also

### CODE REVIEW

**Review by cdeler — APPROVED** [review]
May be I'm a newby, but I had to dig inside cpython source and msdn to realize why it works. 

Specifying `--workers <int>` we enforce the server to use multiple workers processes spawning child processes. It's like a "pre-fork" mode, used, for example, by Apache web server: several child processes handles the same server socket. Unlike in *nix, the only way to share a socket between processes in Win is [WSADuplicateSocket](https://docs.microsoft.com/en-us/windows/win32/winsock/shared-sockets-2), called by `sock.share()`. 

It's what the PR did.

Let me left it there, just for the history :-)

Approved

**Comment by euri10** [comment]
> Let me left it there, just for the history :-)

history thank you ! pretty amazing explanation, I didn't know all that

**Comment by bobfang1992** [comment]
When will this be released? Thanks!

**Comment by cdeler** [comment]
@bobfang1992 here is the release

https://github.com/encode/uvicorn/pull/823

**Comment by bobfang1992** [comment]
awesome.

**Comment by Robby-Sodhi** [comment]
I am having this issue again

**Comment by qqletter** [comment]
I get the same error when use multiple workers on win11(22H2) and uvicorn 0.22.0

**Pull request merged**
