### PR TITLE
draft: support limitation for header and message body

### PR DESCRIPTION
**Pull request by magiskboy**
# Summary

As a webserver, uvicorn should be implemented limitation of header and message body.

In this PR, uvicorn check length of header and message body when parsing, if those is larger than settings, responds as soon as to client

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by zanieb** [comment]
Hi @magiskboy thanks for contributing!

Is there a discussion or GitHub issue that this is resolving?

**Comment by Kludex** [comment]
> Hi @magiskboy thanks for contributing!
> 
> Is there a discussion or GitHub issue that this is resolving?

I think there's an issue about limiting resources, but I don't think this PR addresses what it's trying to address.

**Comment by magiskboy** [comment]
> 

I see that https://github.com/encode/uvicorn/discussions/1726 but, limit header size only support with h11 protocol. In this pr, limitation will be applied to httptools

**Comment by magiskboy** [comment]
@Kludex could you tell me the reason? Do you have any idea?

**Comment by Kludex** [comment]
> @Kludex could you tell me the reason? Do you have any idea?

You need to read this: https://github.com/encode/uvicorn/pull/1684, and the links there.

**Comment by magiskboy** [comment]
I thought about that so parser should be support limitation because protocol is received only fully headers

**Pull request closed without merging**
