### PR TITLE
use IOCP in windows

### PR DESCRIPTION
**Pull request by abersheeran**
https://docs.python.org/3/library/asyncio-policy.html#asyncio.WindowsProactorEventLoopPolicy

### CODE REVIEW

**Review by gvbgduh — CHANGES_REQUESTED** [review]
It might be not a bad idea to bring another implementation of the event loop. But in this implementation, it implicitly replaces the asyncio event loop. It may confuse the user it's generally better to keep things explicit.
So for this particular case, it would be better to create a separate module, like `uvloop`, so it would be possible to specify it with the `--loop` param running the uvicorn server.

**Comment by abersheeran** [comment]
I agree it. I will make changes later and resubmit.

**Comment by gvbgduh** [comment]
@abersheeran looks really good to me. Let's run it with @tomchristie what he thinks.

**Comment by lovelydinosaur** [comment]
Liking it, yup!

**Comment by abersheeran** [comment]
So, why not merge the PR? What else do I need to modify?

**Comment by gvbgduh** [comment]
hey @abersheeran, I'm going to merge it today, but if you could run `./scripts/lint` and then push again it would save some time.

**Review by gvbgduh — APPROVED** [review]

**Comment by gvbgduh** [comment]
Actually, never mind!

**Comment by abersheeran** [comment]
I am sorry that I didn't notice lint, I will use it next time. 😅

**Comment by gvbgduh** [comment]
all good, thanks for the PR!

**Pull request merged**
