### PR TITLE
Debug CI default headers

### PR DESCRIPTION
**Pull request by euri10**
wip

### CODE REVIEW

**Comment by iudeen** [comment]
Another observation in windows...
When I run the tests when my CPU is loaded, it fails. The same passes when the CPU is free.

I loaded CPU by running multiple other (normal) uvicorn servers.

**Comment by euri10** [comment]
I really dont get why on macos we have the httpx client hittiing twice pretty much instantly, it doesnt make any sense

locally on linux I get this:
```
test: 2022-09-27 14:08:52.417361

counter: 0

on_tick: b'Tue, 27 Sep 2022 14:08:52 GMT'

on_tick1: 2022-09-27 16:08:52.466008
INFO:     127.0.0.1:39504 - "GET / HTTP/1.1" 200 OK
2022-09-27 14:08:52

counter: 10

on_tick: b'Tue, 27 Sep 2022 14:08:53 GMT'

on_tick1: 2022-09-27 16:08:53.470282
INFO:     127.0.0.1:39506 - "GET / HTTP/1.1" 200 OK
2022-09-27 14:08:53
```
on macos in CI we get this (https://github.com/encode/uvicorn/actions/runs/3135364683/jobs/5090951410)
```
test: 2022-09-27 11:52:57.553520

counter: 0

on_tick: b'Tue, 27 Sep 2022 11:52:57 GMT'

on_tick1: 2022-09-27 11:52:57.556196
INFO:     127.0.0.1:49244 - "GET / HTTP/1.1" 200 OK
2022-09-27 11:52:57
INFO:     127.0.0.1:49245 - "GET / HTTP/1.1" 200 OK
2022-09-27 11:52:57
```

**Comment by euri10** [comment]
it is as if the `await asyncio.sleep(1)` in the ci on mac os had absolutely no effect

**Comment by iudeen** [comment]
@euri10 did you try in Linux, with an occupied CPU?

So in windows, when I run the test with 92% CPU, the following are the results:

```
============================= test session starts =============================
collecting ... collected 1 item

test_default_headers.py::test_date_headers_update FAILED                 [100%]
test: 2022-09-27 15:27:01.825848

counter: 0

on_tick: b'Tue, 27 Sep 2022 15:27:01 GMT'

on_tick1: 2022-09-27 20:57:01.953032
INFO:     127.0.0.1:58893 - "GET / HTTP/1.1" 200 OK
2022-09-27 15:27:01

counter: 10

on_tick: b'Tue, 27 Sep 2022 15:27:03 GMT'

on_tick1: 2022-09-27 20:57:03.022269
INFO:     127.0.0.1:58896 - "GET / HTTP/1.1" 200 OK
2022-09-27 15:27:03
```

At 25% CPU

```
============================== 1 passed in 1.76s ==============================

Process finished with exit code 0
PASSED                 [100%]
test: 2022-09-27 15:28:24.649544

counter: 0

on_tick: b'Tue, 27 Sep 2022 15:28:24 GMT'

on_tick1: 2022-09-27 20:58:24.725336
INFO:     127.0.0.1:58902 - "GET / HTTP/1.1" 200 OK
2022-09-27 15:28:24

counter: 10

on_tick: b'Tue, 27 Sep 2022 15:28:25 GMT'

on_tick1: 2022-09-27 20:58:25.806437
INFO:     127.0.0.1:58903 - "GET / HTTP/1.1" 200 OK
2022-09-27 15:28:25
```

**Comment by euri10** [comment]
nope, I've got 48 cores so it's rather hard, this said once cpu is busy the delay is 2s and franckly this seems logical to me, well at least not absurd, while the macos in CI depicts a woooping 0s delay, and this really I cant get my head around.

**Comment by iudeen** [comment]
So, I closed all my applications, and got my CPU to less than 10%, and look at the tests now...got 0 seconds!

```
============================= test session starts =============================
collecting ... collected 1 item

test_default_headers.py::test_date_headers_update FAILED                 [100%]
test: 2022-09-27 15:46:34.032260

counter: 0

on_tick: b'Tue, 27 Sep 2022 15:46:34 GMT'

on_tick1: 2022-09-27 21:16:34.195891
INFO:     127.0.0.1:59102 - "GET / HTTP/1.1" 200 OK
2022-09-27 15:46:34
INFO:     127.0.0.1:59103 - "GET / HTTP/1.1" 200 OK
2022-09-27 15:46:34

counter: 10

on_tick: b'Tue, 27 Sep 2022 15:46:35 GMT'

on_tick1: 2022-09-27 21:16:35.291409
```

**Comment by euri10** [comment]
at least you can locally reproduce, I havent been able, this said I'm out of ideas as to why we have those 2 httpx connections at the  same time, there seems to be no wait in between as far as I can tell reading the logs

**Comment by euri10** [comment]
one could launch the test with yappi (https://github.com/sumerc/yappi#profile-an-asyncio-application), throwing ideas

**Comment by iudeen** [comment]
Just a thought outside the box, do we have to use the `on_tick` function to update something that is very time sensitive, given the uncertainty of it?🤔

**Comment by iudeen** [comment]
Wait happens, proven by printing `time.time_ns()`

| Start Time (ns)        | Endtime (ns)           | Difference (ns) | Difference (s) | Start Time (UTC)    | End Time (UTC)      | Difference | Test Result |
| ---------------------- | ---------------------- | --------------- | -------------- | ------------------- | ------------------- | ---------- | ----------- |
| 1664360145262000000.00 | 1664360146307550000.00 | 1045549824      | 1.04555        | 28-09-2022 10:15:45 | 28-09-2022 10:15:46 | 1          | Pass        |
| 1664360280299580000.00 | 1664360281327130000.00 | 1027550208      | 1.02755        | 28-09-2022 10:18:00 | 28-09-2022 10:18:01 | 1          | Pass        |
| 1664360371812710000.00 | 1664360372849860000.00 | 1037150208      | 1.03715        | 28-09-2022 10:19:31 | 28-09-2022 10:19:31 | 0          | Fail        |
| 1664360509880850000.00 | 1664360510910240000.00 | 1029390080      | 1.02939        | 28-09-2022 10:21:49 | 28-09-2022 10:21:49 | 0          | Fail        |

This may prove that wait happens (see Difference (ns)), ~~but `datetime` does not update. Or the information is lost when we do `dt.datetime.strptime`~~

**Pull request closed without merging**
