### PR TITLE
Improved wsgi middleware, mainly a copy of a2wsgi

### LINKED ISSUE #371: WSGI middleware should stream request body, rather than loading it all at once.
Hi! I'm deploying a Django app with uvicorn, running on k8s. Our containers were being killed, and I've found that when users upload large files, uvicorn increases memory usage, and slows to a crawl. Eventually causing an OOM.

I'm not sure where this is happening yet, and I suspect could be related to https://github.com/django/channels/pull/1251, but I did a bit more digging and I'm not totally sure. I've tried running uvicorn in wsgi mode, and completely removed channels from the django install, and I'm getting the same behavior. File uploads are being loaded into memory (rather than streaming to disk, as they should be), and upload speeds slow to a crawl. The same app running on gunicorn works fine.

The file I'm testing with is about 470mb.

### PR DESCRIPTION
**Pull request by euri10**
Should fix https://github.com/encode/uvicorn/issues/371
I added types as well

### CODE REVIEW

**Comment by Kludex** [comment]
I guess we only need to remove the types on the `wsgi.py` file and rebase?

**Comment by abersheeran** [comment]
I think it might be more convenient to directly use [a2wsgi](https://github.com/abersheeran/a2wsgi) as a dependency. As far as I know, Uvicorn and Starlette both have WSGIMiddleware, which is a duplicate. And it will cause the changes in one of the items to not be quickly reflected in the other item.

**Comment by euri10** [comment]
that's indeed a good idea, my only concern is the types, not sure how that would work since we're not using the same base

**Comment by Kludex** [comment]
We probably should:
1. Sync with Starlette. Should we only remove from `uvicorn` or removing on `starlette` also makes sense?    
2. If we want to remove it from `uvicorn` only, add a `DeprecationWarning`, recommending [a2wsgi](https://github.com/abersheeran/a2wsgi). Then later on we can remove it.
3. Update documentation.

**Comment by Flauschbaellchen** [comment]
Hi,

I run into the same problem as described in #371 as my app needs to support uploads of large files which are often 1GB or much bigger.
I would like to support here as much as I can. Do you need someone for testing purposes?

**Pull request closed without merging**
