### PR TITLE
e2e testing for gunicorn worker

### PR DESCRIPTION
**Pull request by euri10**

### CODE REVIEW

**Comment by euri10** [comment]
interesting windows only error on an unrelated not-closed socket ;)

**Comment by euri10** [comment]
> interesting windows only error on an unrelated not-closed socket ;)

solved in https://github.com/encode/uvicorn/pull/1080

**Comment by euri10** [comment]
well the exit 3 solved in https://github.com/encode/uvicorn/pull/1077 is well demonstrated (and solved once that patch is applied)

**Comment by euri10** [comment]
only big issue with that e2e approach is that it slows down the testing a lot.

**Comment by Kludex** [comment]
Can we can run them in parallel? How slow it becomes?

**Comment by euri10** [comment]
```
========================================================================================================== slowest durations ==========================================================================================================
77.30s setup    tests/e2e/test_gunicorn.py::test_gunicorn_default[default.py-0]
28.79s setup    tests/e2e/test_gunicorn.py::test_gunicorn_default[startup_failed.py-137]
2.60s call     tests/e2e/test_gunicorn.py::test_gunicorn_default[default.py-0]
2.10s call     tests/e2e/test_gunicorn.py::test_gunicorn_default[startup_failed.py-137]
```

settings up the docker images is what takes the most time

**Comment by Kludex** [comment]
We should try to cache those images then, I guess. :thinking: 

EDIT: Did you mean the image build or the container startup? :thinking:

**Comment by euri10** [comment]
> Can we can run them in parallel? How slow it becomes?

I tried pytest-xdist which blows the test suite, I think mostly because ports used for each run_in_server are the same so maybe something worh looking at, not sure

**Comment by Kludex** [comment]
> I tried pytest-xdist which blows the test suite, I think mostly because ports used for each run_in_server are the same so maybe something worh looking at, not sure

I didn't mean on the pytest level, I mean on the CI, creating two jobs in parallel.

**Comment by euri10** [comment]
> > I tried pytest-xdist which blows the test suite, I think mostly because ports used for each run_in_server are the same so maybe something worh looking at, not sure
> 
> I didn't mean on the pytest level, I mean on the CI, creating two jobs in parallel.

ok I seperated them into 2 jobs using markers in pytest, would like to see once [this](https://github.com/encode/uvicorn/pull/1077) is merged

**Pull request closed without merging**
