### PR TITLE
Add `asgi` field to the lifespan scope

### LINKED ISSUE #753: Lifespan scope is missing asgi dict
the lifespan scope (https://asgi.readthedocs.io/en/latest/specs/lifespan.html#scope) is missing the asgi dict

prompted by

_Originally posted by @florimondmanca in https://github.com/encode/uvicorn/pull/751_

### PR DESCRIPTION
**Pull request by euri10**
fix #753 
note that spec version is 2.0 according to https://asgi.readthedocs.io/en/latest/specs/lifespan.html#version-history

### CODE REVIEW

**Comment by euri10** [comment]
should we add tests for this ?

**Comment by florimondmanca** [comment]
> should we add tests for this ?

Ideally, yup! 😄 I think there are already some "unit" tests related to the `asgi_version`, we can take inspiration from them to check that uvicorn passes this info when doing the lifespan dance.

**Comment by euri10** [comment]
mmm we test scope and asgi version here on the protocol level, and only for the http protocol this said (this could be done for the ws one too)
https://github.com/encode/uvicorn/blob/fbce393fd34038a589bba02e759b0f051f52ad84/tests/protocols/test_http.py#L690-L702

one simple test could be in `test_lifespan.py` with somethings like this ?
or should we mock the lifespan protocol the way we moch the http one in tests and test the scope rightness there ?

```
    async def app(scope, receive, send):
        nonlocal startup_complete, shutdown_complete
+++ assert scope.get("asgi") +++
        message = await receive()
```

**Comment by euri10** [comment]
ok added some tests for both cases , asgi 2 or 3

**Review by florimondmanca — APPROVED** [review]
Very nice!

**Pull request merged**
