### PR TITLE
Config coverage increase

### PR DESCRIPTION
**Pull request by euri10**
Little steps towards https://github.com/encode/uvicorn/issues/102

Added tests to increase config.py coverage (a little bit of main.py too), went from 81 to 99%.

Incidentally when I added the ini log config file in that commit (aff30ae3708603c70f96570c5c4a9ea909915276) it broke the http protocol logs tests [here](https://github.com/encode/uvicorn/blob/a839da2564e5168c6e99c3b22819950f26f7d178/tests/protocols/test_http.py#L171)  and it looks the fix from #512 is necessary or no logs are sent indeed.

Also trying to understand the specifics of <3.7 for loggers it appears to me the check is not necessary anymore (last commit 32b2c727f31d9429427838b9afc2b587d9f28f9d)

### CODE REVIEW

**Comment by euri10** [comment]
tests pass fine locally, dunno what travis is currently doing, all tests are failing and logs are not possible to fetch

**Comment by euri10** [comment]
need to get why pypy timeout

**Review by lovelydinosaur — APPROVED** [review]
Seems okay, yup.

I'd generally suggest that we try to keep PRs split up wherever ossible (eg. the change in the `disable_existing_loggers=False` seems unrelated to the coverage, as does the `sys.version_info < (3,7)` case. Having said that I don't think we should let those block this from progressing.

Looks like there's some conflicts that'll need resolving, but otherwise, great - let's move on with this! 😃

**Comment by euri10** [comment]
> Seems okay, yup.
> 
> I'd generally suggest that we try to keep PRs split up wherever ossible (eg. the change in the `disable_existing_loggers=False` seems unrelated to the coverage, as does the `sys.version_info < (3,7)` case. Having said that I don't think we should let those block this from progressing.
> 
> Looks like there's some conflicts that'll need resolving, but otherwise, great - let's move on with this!

ok I rebased it and all tests pass

I'm sorry for not separating them and will keep them seperated next time.

just one thing I'd like you to confirm,not sure you saw it, it's the change here in uvicorn/config.py

just asking because you seemed not ok about it in https://github.com/encode/uvicorn/issues/511

**Comment by lovelydinosaur** [comment]
> just one thing I'd like you to confirm, not sure you saw it, it's the change here in uvicorn/config.py

Well, *ideally* keep it separate from this PR.

I'm not sure, I'm not convinced about it, but we also get a lot of feedback around the behaviour there, so... 🤷‍♂️

**Pull request merged**
