### PR TITLE
Create setting/flag to enable/disable X-Forwarded-Port

### PR DESCRIPTION
**Pull request by victor-torres**
# Summary

Create a new setting/flag to enable/disable X-Forwarded-Port to populate remote address info.

This flag is disabled by default. Command line options are: 
- `--forwarded-port`
- `--no-forwarded-port`

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by victor-torres** [comment]
This pull request is addressing the issue described in #1974

**Comment by victor-torres** [comment]
There's a failing test case in `tests/supervisors/test_multiprocess.py` that I don't think is related to this PR. 
It fails on Python 3.9 running on macOS.

I think this PR is ready for review. Let me know if I can help with anything else or if there's anything that could be improved here :D

**Comment by Kludex** [comment]
Do we need to add a new flag?

**Comment by victor-torres** [comment]
I don't mind considering X-Forwarded-Port (if available) by default if already checking for X-Forwarded-For. 

My decision to include a new flag was to avoid changing the default behaviour, something that some maintainers and some users usually ask for. 

But I can totally remove the flag and make it be considered by default +1 

Just let me know.

**Comment by Kludex** [comment]
Let's take a step back here, and continue the discussion on https://github.com/encode/uvicorn/issues/1974#issuecomment-2401602267, please.

**Comment by Kludex** [comment]
I'll be closing this until we have a decision on the issue.

I don't think we want this to be a parameter anyway.

**Pull request closed without merging**
