### PR TITLE
Pinning h11 and python-dotenv to min versions

### PR DESCRIPTION
**Pull request by euri10**
Following https://gitter.im/encode/community?at=5f71fafdb39cb873c08b5c9a and in light of https://github.com/encode/uvicorn/pull/772#issuecomment-700012365 and https://github.com/encode/uvicorn/issues/788

this removes the max dependencies and just sets the minimum version

### CODE REVIEW

**Comment by florimondmanca** [comment]
I think we might want to start with just unpinning / minpinning h11?

**Comment by euri10** [comment]
> I think we might want to start with just unpinning / minpinning h11?

ok I unpinned only h11 and also python-dotenv, there's no reason for it to be so strict

**Review by florimondmanca — APPROVED** [review]
Okay, sounds good. Let's just perhaps update the PR title to reflect what this does exactly. (Though that's going to contain an "_and_" somewhere, but at least we'd know what this PR does and it's easier to track in changelogs. :-))

**Comment by euri10** [comment]
mmm cant merge...what happened

**Comment by euri10** [comment]
haha ok I got it

**Pull request merged**
