### PR TITLE
Make dependencies optional

### LINKED ISSUE #219: Use optional package installs.
Instead of the platform detection I’d like uvicorn to use optional installs.

* `pip install uvicorn` - Just the package itself.
* `pip install uvicorn[standard]` - uvloop/httptools/websockets
* `pip install uvicorn[pure]` - asyncio/h11/wsproto
* `pip install uvicorn[full]` - Everything

### PR DESCRIPTION
**Pull request by carlwgeorge**
resolves #219

### CODE REVIEW

**Comment by almarklein** [comment]
I think this also closes #135; `[all]` would simply not work on Windows.

**Comment by lovelydinosaur** [comment]
@almarklein Yes. In fact we should close that now, since it's not the approach we want to take.

**Comment by carlwgeorge** [comment]
Does this need any other changes to merge?

**Comment by lovelydinosaur** [comment]
I think it's exactly what we want yup, but probably best to wait for a 0.4 release before we pull it in.

**Comment by almarklein** [comment]
I'd like to get this in. I'd have time to rebase this, if @carlwgeorge is ok with that.

**Comment by carlwgeorge** [comment]
@almarklein Sure, go for it.

**Comment by lovelydinosaur** [comment]
Closing in favor of #298

**Pull request closed without merging**
