### PR TITLE
Add note on 'UVICORN_' prefixed settings and '--env-file'

### LINKED ISSUE #1319: dotenv file not loaded correctly
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Uvicorn does not load the dot env file as expected when running it via over the command line or via `uvicorn.run`.

### Steps to reproduce the bug

File `bug.py`:
```py
import uvicorn


if __name__ == '__main__':
    uvicorn.run('bug:app', host='localhost', env_file='.env')

# Uvicorn's example app:
async def app(scope, receive, send):
    assert scope['type'] == 'http'

    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ],
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })
```
File `.env`:
```
UVICORN_PORT=8081
PORT=8081
```
Shell:
```sh
$ uvicorn bug:app --env-file .env
or
$ python bug.py
```
Output (both times):
```
/venv/bin/python3.10 /bug.py
INFO:     Loading environment from '.env'
INFO:     Started server process [11355]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
```

### Expected behavior

Server running on port 8081.

### Actual behavior

Server running on port 8000:
```
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
```

### Debugging material

_No response_

### Environment

 - `uvicorn --version`
   - `Running uvicorn 0.16.0 with CPython 3.10.0 on Linux`
 - Run commands:
   - `uvicorn bug:app --env-file .env`
   - `python bug.py`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lovelydinosaur**
Closes https://github.com/encode/uvicorn/issues/1319

Rendered docs now look like...

Screenshot 2022-02-11 at 12 07 49

### CODE REVIEW

**Comment by Kludex** [comment]
Maybe we can add a parenthesis with: "(--env-file)", just to be clear? 🤔

**Review by Kludex — APPROVED** [review]
:+1:

**Comment by lovelydinosaur** [comment]
@Kludex Good call.

As it happens it looks like we don't currently have `--env-file` in *this* part of the docs. (Tho let's treat that separately. It might be that there's more than one setting/flag that's not consistently included throughout our docs, perhaps?)

**Comment by Kludex** [comment]
Yeah... I'm going to be honest... I didn't know the `--env-file` existed until that issue was opened 😆

**Pull request merged**
