### PR TITLE
Fix pip upgrade in TestSuite checks

### PR DESCRIPTION
**Pull request by adnaanbheda**

### CODE REVIEW

**Comment by adnaanbheda** [comment]
@Kludex Sorry didn't notice that you had already created a PR, welp, feel free to close this!

**Comment by Kludex** [comment]
I didn't solve it yet. :eyes: 

This PR is also not a solution, because it doesn't work locally.

**Comment by adnaanbheda** [comment]
@Kludex on Windows? I tried it out, seems fine 

```
C:\Windows\System32>python -m pip install -U pip
Requirement already satisfied: pip in c:\users\adnaan\appdata\local\programs\python\python310\lib\site-packages (22.2.2)
Collecting pip
  Using cached pip-22.3-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.2
    Uninstalling pip-22.2.2:
      Successfully uninstalled pip-22.2.2
Successfully installed pip-22.3
```

**Comment by Kludex** [comment]
`./scripts/install`

**Comment by Kludex** [comment]
Locally you are supposed to run the script above to install the dependencies.

**Comment by adnaanbheda** [comment]
Let me try, curious, what's the error you're getting ?

EDIT: 
Okay, gotcha, `python3 -m venv/bin/pip` is stupid, okay lemme fix this.

**Review by Kludex — APPROVED** [review]
Thank you @adnaanbheda :pray:

**Comment by Kludex** [comment]
What is the difference between `"$PIP"` and `${PIP}`?

**Pull request merged**
