### PR TITLE
Allow passing a custom loop setup function instead of None

### PR DESCRIPTION
**Pull request by gnir-work**
# Summary
Support passing a custom IOLoop setup function in order to support running `uvicorn` in custom ioloop implementation other that the default and `uvloop`.

For example this feature will allow using [this monitored IOLoop](https://github.com/gnir-work/monitored-ioloop) inside `uvicorn` applications :)

Link to discussions thread - https://github.com/encode/uvicorn/discussions/2256

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by Kludex** [comment]
@gnir-work I don't want to have 2 similar parameters. I'd prefer us to go with this approach: https://github.com/encode/uvicorn/pull/2130/files (which turns the `--loop` into your `--loop-setup`.

If you want to move this forward, the best approach would be to continue that PR - fixing the pipeline, etc.

**Comment by hxnir** [comment]
No problem :)
Just a quick question - How should I go about it? Should I fork the `graingert:uvicorn` repo and open another PR?
I can also update the current diff to be in the same spirit as the [PR you mentioned](https://github.com/encode/uvicorn/pull/2130/files)

**Comment by Kludex** [comment]
I would add a remote on his repo, get the branch, and push to your fork, and then create a PR.

**Comment by gnir-work** [comment]
Closing this PR in favor of https://github.com/encode/uvicorn/pull/2435.
Will update it from draft to open as soon as everything is passing :)

**Pull request closed without merging**
