### PR TITLE
tests: test multiprocess with sockets

### PR DESCRIPTION
**Pull request by iudeen**
Covers `server.py` line 105-125

https://github.com/encode/uvicorn/blob/d613cbea388bafafb6f642077c035ed137deea61/uvicorn/server.py#L105-L125

Before PR (Windows):
```
Name                                           Stmts   Miss     Cover   Missing
-------------------------------------------------------------------------------
uvicorn\server.py                                156     26    83.33%   105-125, 160-163, 245-247, 263, 274-277, 307-310
-------------------------------------------------------------------------------
TOTAL                                           4994     64    98.72%
```
Before PR (Ubuntu):
```
Name                                           Stmts   Miss     Cover   Missing
-------------------------------------------------------------------------------
uvicorn/server.py                                171     22    87.13%   115-125, 141, 160-163, 245-247, 263, 274-277, 307-310
-------------------------------------------------------------------------------
TOTAL                                           5102     67    98.69%
```

After PR (Windows):
```
Name                                           Stmts   Miss     Cover   Missing
-------------------------------------------------------------------------------
uvicorn\server.py                                156     15    90.38%   160-163, 245-247, 263, 274-277, 307-310
-------------------------------------------------------------------------------
TOTAL                                           5003     54    98.92%
```

After PR (Ubuntu):
```
Name                                           Stmts   Miss     Cover   Missing
-------------------------------------------------------------------------------
uvicorn/server.py                                171     16    90.64%   141, 160-163, 245-247, 263, 274-277, 307-310
-------------------------------------------------------------------------------
TOTAL                                           5111     63    98.77%
```

### CODE REVIEW

**Comment by iudeen** [comment]
`Python 3.9 macos` fails on a testcase unrelated to this PR. 🤔

**Comment by Kludex** [comment]
It should be related to the unique port fixture.

**Comment by iudeen** [comment]
I might want to test logs here, that should make more sense.

**Comment by Kludex** [comment]
On the windows logic, is there a way to check if the socket is "shared" or something? :thinking: 

I think we need to improve the goal of our test here. I'm feeling this test is only for the purpose of increasing the coverage.

**Comment by iudeen** [comment]
I'll check!🤞

**Comment by iudeen** [comment]
May be something like this?

_referred from trio_

```
@pytest.mark.skipif(not hasattr(tsocket, "fromshare"), reason="windows only")
async def test_fromshare():
    a, b = tsocket.socketpair()
    with a, b:
        # share with ourselves
        shared = a.share(os.getpid())
        a2 = tsocket.fromshare(shared)
        with a2:
            assert a.fileno() != a2.fileno()
            await a2.send(b"x")
            assert await b.recv(1) == b"x"
```

**Comment by Kludex** [comment]
Any progress here?

**Comment by iudeen** [comment]
Hey! Was busy with work, I'll resume this week! 

Thanks!

**Comment by Kludex** [comment]
I'm closing this for housekeeping. :eyes:

Whenever you have time to work on them, feel free to reopen it. :pray:

**Pull request closed without merging**
