### PR TITLE
Add no-lifespan worker class

### PR DESCRIPTION
**Pull request by niccolomineo**
I'd like to suggest a courtesy worker class with the lifespan disabled, proving useful for Django users in particular.

### CODE REVIEW

**Review by pauloxnet — APPROVED** [review]

**Comment by Kludex** [comment]
Hi @niccolomineo,

Thanks for the PR!

I'd prefer to not have another custom worker, it's too simple to be created from the user's point of view.

And I think the documentation explains how to add a custom configuration for the worker? If not, PR welcome for that, if we can find a good spot in the docs.

Please don't hate me when you see me at PyCon IT. 🙏

**Comment by niccolomineo** [comment]
Hi Marcelo, no hurt feelings! Do you believe it could still be useful to mention the no-lifespan config in a specific section of the docs / README to help Django users in dark?

**Comment by Kludex** [comment]
I just read the docs, this part specifically: https://www.uvicorn.org/deployment/#gunicorn

Isn't it enough? Or what do you propose?

**Comment by niccolomineo** [comment]
What about mentioning that turning off the lifespan is the way to have the worker class function properly with Django?

**Comment by Kludex** [comment]
I think the docs are pretty agnostic in regard to web frameworks, wouldn't that make more sense to be on https://docs.djangoproject.com/en/4.1/howto/deployment/asgi/uvicorn/? :thinking:

**Comment by pauloxnet** [comment]
Thanks for your useful feedback on this PR @Kludex and you will be always welcome at PyCon Italia 😄

**Comment by niccolomineo** [comment]
> I think the docs are pretty agnostic in regard to web frameworks, wouldn't that make more sense to be on https://docs.djangoproject.com/en/4.1/howto/deployment/asgi/uvicorn/? :thinking: 

Sounds reasonable to me. Thank you.

**Pull request closed without merging**
