### PR TITLE
Support Python 3.12

### PR DESCRIPTION
**Pull request by Kludex**

### CODE REVIEW

**Comment by graingert** [comment]
The build is failing on
`uvicorn/loops/uvloop.py:7: error: Module has no attribute "EventLoopPolicy"  [attr-defined]`

This is fixed by https://github.com/MagicStack/uvloop/pull/573

**Review by graingert — APPROVED** [review]

**Comment by Kludex** [comment]
This is hanging on Windows.

**Comment by jcheng5** [comment]
The hang is fixed by https://github.com/encode/uvicorn/pull/2145 so I pulled this commit into that one. Hope that's OK.

**Comment by Kludex** [comment]
- Closed by https://github.com/encode/uvicorn/pull/2145

**Pull request closed without merging**
