### PR TITLE
Add coverage-conditional-plugin setup

### PR DESCRIPTION
**Pull request by Kludex**
Remake of #1159

Related to #1157 and #102

I've accidentally deleted my fork, so I'll have to recreate some PRs, jfyk.

@euri10 @tomchristie What do you think about this?

### CODE REVIEW

**Comment by euri10** [comment]
I think it's cool

**Comment by lovelydinosaur** [comment]
Yeah I don't have a problem with that.

**Comment by Kludex** [comment]
Cool! With this I'll try to push forward the 100% coverage in the following weeks :)

If no further complains, would someone be gentle to approve this? :pray:

**Review by euri10 — APPROVED** [review]

**Comment by Kludex** [comment]
Thanks @euri10 :)

**Pull request merged**
