### PR TITLE
Add ssl support.

### PR DESCRIPTION
**Pull request by songww**
#146

### CODE REVIEW

**Review by lovelydinosaur — COMMENTED** [review]
Looking good!

Any idea which projects I should look at to help when I add documentation for this?

**Comment by songww** [comment]
gunicorn  @tomchristie 
command line options and `create_ssl_context` are same as gunicorn.

**Comment by woile** [comment]
hey @songww can you fix the conficts? I will try to add some docs when merged

**Comment by i-zaitsev** [comment]
When do you think this PR is going to be merged?

**Comment by lovelydinosaur** [comment]
@devforfu It's a little out of date with master. If anyone wants to make a revised pull request, bringing this work up to date, then I'd be very happy to look at getting it merged in. 👍

**Comment by woile** [comment]
I'll try to continue with this work this week if everyone is ok

**Comment by i-zaitsev** [comment]
@tomchristie @Woile Ok, great! 

P.S.: Get there after reading @Woile [post](https://woile.github.io/posts/local-https-development-in-python-with-mkcert/) and attempt to enable local HTTPS :) Would be great have this PR, as well as some notes about why we could need this into docs.

**Comment by lovelydinosaur** [comment]
@Woile Awesome post, too!

We might want to consider linking to that from the docs once this is in.

**Comment by bravetheheat** [comment]
Excited for this PR. Need it for an enterprise implementation of uvicorn.

**Comment by lovelydinosaur** [comment]
Superseded by #294

@bravetheheat Great! Landing very shortly.

**Pull request closed without merging**
