### PR TITLE
Initial pass at '--metrics' flag

### PR DESCRIPTION
**Pull request by lovelydinosaur**
```shell
uvicorn$ venv/bin/uvicorn example:App --metrics --log-level error
* Uvicorn running on http://127.0.0.1:8000 🦄 (Press CTRL+C to quit)
PERF: App latency: 0.000013s. App concurrency: 192. Connections: 192.
PERF: App latency: 0.000014s. App concurrency: 192. Connections: 192.
PERF: App latency: 0.000014s. App concurrency: 192. Connections: 192.
PERF: App latency: 0.000013s. App concurrency: 192. Connections: 192.
PERF: App latency: 0.000013s. App concurrency: 192. Connections: 192.
PERF: App latency: 0.000014s. App concurrency: 133. Connections: 133.
PERF: App latency: 0.000013s. App concurrency: 106. Connections: 106.
PERF: App latency: 0.000013s. App concurrency: 146. Connections: 146.
PERF: App latency: 0.000013s. App concurrency: 124. Connections: 124.
PERF: App latency: 0.000013s. App concurrency: 133. Connections: 133.
PERF: App latency: 0.000013s. App concurrency: 0. Connections: 0.
^C```

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Related: https://github.com/django/daphne/issues/118

**Comment by JohnDoee** [comment]
This solution starts counting before the ASGI application is created, how important are the stats regarding "initial request" -> "ASGI app started" ?

In django/daphne#118 you mention "middleware" (or proxy ASGI app as it would probably be), such solution would not log any stats before the application starts.

**Comment by lovelydinosaur** [comment]
@JohnDoee - I'd envisage it like this...

The server would continuously be monitoring the metrics (eg. at `connection_made`, `connection_lost` and whatever other points we need to measure), however we wouldn't continuously be sending those metrics out.

Instead the server would ensure that the app is called with new "metrics" ASGI scope type on a recurring basis (say ~once per second, or whatever the server has configured) - The app would then be able to handle / broadcast / make that information visible over an HTML stats page.

This PR doesn't tackle any of that and was more just a starting point for trying things out. (It just deals with logging some info to stdout)

**Comment by lovelydinosaur** [comment]
Closing this off for now. May come back to it for 1.2 and implement an ASGI-messaging based solution.

**Pull request closed without merging**
