### PR TITLE
tests: ignore test on supervisors init file

### PR DESCRIPTION
**Pull request by Kludex**
Both classes are already being tested on `test_reload.py`. I don't feel the need to reach those lines in the tests, do you?

I'm accepting suggestions on how to test it if so :)

### CODE REVIEW

**Comment by euri10** [comment]
> Both classes are already being tested on `test_reload.py`. I don't feel the need to reach those lines in the tests, do you?
> 
> I'm accepting suggestions on how to test it if so :)

good question, this is not about testing the classes themselves here but more to check the import flow, so I agree I dont see a way to test it easily.
an idea @florimondmanca ?

**Comment by Kludex** [comment]
We can work with pip and uninstall/install (back to the previous state) watchgod for testing.

Something like this (but organized and maybe being a fixture, ofc):
```python
import pip
pip.main(['uninstall', package]) 
# test for statreload
pip main(['install', package])
```

Or maybe mocking the globals object so it doesn't have the watchdog? I'm not even sure this is possible :kissing:

**Comment by euri10** [comment]
to be fair I think the pragma here is well justified, let' see what other think but for me this is good enough, adding more is needlessly complex

**Review by florimondmanca — APPROVED** [review]
Yes, I think we can go with a simple no-cover here.

**Review by euri10 — APPROVED** [review]

**Pull request merged**
