### PR TITLE
Revert raise `ClientDisconnected` on HTTP (#2276)

### PR DESCRIPTION
**Pull request by ninoseki**
# Summary

Revert #2220 to fix(close) #2271.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by EwertonDCSilv** [comment]
Por favor, revertam essa PR, ela esta quebrando minha aplicação FastAPI !

**Comment by Kludex** [comment]
> Por favor, revertam essa PR, ela esta quebrando minha aplicação FastAPI !

Blz.

**Comment by ninoseki** [comment]
Excuse me,  I read your comments through Google Translate but I’m not sure I understand them correctly. Please let me know in English if there is anything I should change.

**Comment by Kludex** [comment]
No, it's good.

**Review by Kludex — APPROVED** [review]

**Pull request merged**
