### PR TITLE
Should not set log level for default logger

### PR DESCRIPTION
**Pull request by kigawas**
This is relevant to #630 and #674, generally uvicorn is not supposed to play with the default root logger.

Since this is a trivial fix, it should not introduce any bugs.

### CODE REVIEW

**Comment by kigawas** [comment]
Lint errors occurred. Need a fix on master, I guess.

**Comment by euri10** [comment]
> Lint errors occurred. Need a fix on master, I guess.

which occurred, can you rebase please ?

**Comment by kigawas** [comment]
Updated against upstream

**Review by euri10 — APPROVED** [review]

**Comment by euri10** [comment]
thanks @kigawas

**Pull request merged**
