### PR TITLE
Defaults ws max_size on server to 16MB

### PR DESCRIPTION
**Pull request by euri10**
Rough attempt at solving https://github.com/encode/uvicorn/issues/306

There are a few points I'm not sure:

1. seems like this can be implemented only on `WebSocketProtocol` but the truth is I didn't find anything relevant for `WSProtocol`
2. In `class WebSocketCommonProtocol(asyncio.Protocol):` the default max_size is 2**20 (1MB) so I wrote a new test that sends 1 more byte than this default, using a default config on the server side that uses a 16MB default (following [hypercorn default](https://gitlab.com/pgjones/hypercorn/blob/master/hypercorn/config.py#L77)), would you want to see more tests, which ones  (send 1 bytes more that default config of 16MB > 1009 , anything else ?_)

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Okay looks good. Shall we call this `ws_max_size` and make sure to push it all the way through to being a configurable setting? (Including the cli)

**Comment by euri10** [comment]
Will do it asap, kind of swamped with work now.

**Comment by euri10** [comment]
OK @tomchristie I changed the name and pushed it all the way up so that it's configurable,
there are 2 things I'd like feedback on before advancing:

1. is the 16MB default good for you ?
2. since the option is configurable only for the `WebSocketProtocol` (I didnt find anything relevant for the `WSProtocol`) should we add a warning / sys.exit(1) if someone uses the `--ws-max-size` with the `--ws=wsproto` ? I added a note in the docs in case

**Comment by deepankarm** [comment]
@euri10 Is there any reason this wasn't merged?

**Comment by euri10** [comment]
Yes we need a reviewer's approval to merge something.

**Comment by jjehl** [comment]
Maybe have you find a reviewer ? This limitation of 1MB could be a real problem when using uvicorn.  And the patch appear to be simple : 
`super().__init__(ws_handler=self.ws_handler, ws_server=self.ws_server, max_size=self.config.websocket_max_message_size)`

**Comment by castaway2000** [comment]
I am also finding this to be a major hindrance in some of the work i am doing. is there a way we can merge this in?

**Comment by darthlegit** [comment]
eagerly awaiting this.

**Pull request closed without merging**
