### PR TITLE
Moved warning about missing ws library only in upgrade case

### PR DESCRIPTION
**Pull request by euri10**
Follow up to #1352 
Solves the issue raised in https://github.com/encode/uvicorn/pull/1352#discussion_r804502418

### CODE REVIEW

**Comment by Kludex** [comment]
Why is there a need for coverage downgrade if there's a _no pragma_?

**Comment by euri10** [comment]
I added it in this PR to try fix the coverage downgrade but it wasn't enough so I fixed it like that, which is bad, but the pragma wasnt in the previous commit and the coverage should have dropped there, so really I dont know, seems flacky

**Review by lovelydinosaur — APPROVED** [review]
Similarly to @Kludex I also don't get the `nocover`/coverage change.
But also I don't care enough about that for it to block the PR.

(Because correctness wins as a priority)

**Comment by euri10** [comment]
Ok I merge and will dig into the coverage stuff later

**Pull request merged**
