### PR TITLE
Release version 0.11.6

### PR DESCRIPTION
**Pull request by tiangolo**
Release version 0.11.6.

I added notes in the changelog for the recent PRs after version 0.11.6:  https://github.com/encode/uvicorn/pull/660

All the changes are docs or bugfixes, so I just bumped the patch version.

---

Note: After/if merging, this would require adding a manual release in GitHub, including the new changelog items.

### CODE REVIEW

**Comment by tiangolo** [comment]
I'm not sure if there is a convention for the format of the messages in the changelog, I based it on the previous ones.

The current order in this PR is latest/newest PRs merged on top. The same way that latest version numbers are on top.

I'm not including PR numbers nor contributors, and not including small changes like typos.

@tomchristie let me know if I should adjust that or if you would prefer to change the info in the changelog somehow.

**Comment by lovelydinosaur** [comment]
> The current order in this PR is

Don't really mind about ordering here.

> I'm [...] not including small changes like typos.

Indeed. We should only include *behavioural* changes in the release notes. Docs changes shouldn't really be in the release notes (since they're not actually part of the package release) nor should refactorings (since they ought to be transparent to the end user).

**Comment by lovelydinosaur** [comment]
And thanks so much for cracking on with this! 😃

**Comment by tiangolo** [comment]
Perfect! Done :heavy_check_mark: 

...I wish I could do more, I keep promising myself I'll do more here and on Starlette and then the other issues/PRs in FastAPI hold me there :facepalm: :sweat_smile:

**Comment by lovelydinosaur** [comment]
Don't sweat it, we're all doing what we can, where we can. 😃

**Review by lovelydinosaur — APPROVED** [review]

**Comment by lovelydinosaur** [comment]
@tiangolo Ya fancy [issuing the release](https://github.com/encode/uvicorn/releases)? Otherwise I'm happy to sort that.

tag: 0.11.6
title: Version 0.11.6
description: * Fix overriding the root logger.

**Comment by tiangolo** [comment]
Awesome, thanks! :tada: 

> Ya fancy issuing the release?

Sure thing! :star_struck: :rocket: :heavy_check_mark:

**Pull request merged**
