### PR TITLE
Rename subprocess module to avoid clash with stdlib

### PR DESCRIPTION
**Pull request by matgnt**
Same problem as with #1426 and logging

I got errors like:
```
AttributeError: partially initialized module 'subprocess' has no attribute 'PIPE' (most likely due to a circular import)
```

### CODE REVIEW

**Comment by euri10** [comment]
how do you get that error please @matgnt ?

**Comment by matgnt** [comment]
> how do you get that error please @matgnt ?

I'm on latest master (dcc5c9681d3dfb5795dee758ba83268a0377ea17)
Runnin in a venv with Python 3.10.0 installed everything from requirements via pip and then I run (from the root directory):
```
$ python uvicorn/main.py --help
Traceback (most recent call last):
  File "/workspaces/type-tree/uvicorn/uvicorn/main.py", line 3, in <module>
    import platform
  File "/usr/local/lib/python3.10/platform.py", line 119, in <module>
    import subprocess
  File "/workspaces/type-tree/uvicorn/uvicorn/subprocess.py", line 12, in <module>
    from uvicorn.config import Config
  File "/workspaces/type-tree/uvicorn/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/workspaces/type-tree/uvicorn/uvicorn/config.py", line 1, in <module>
    import asyncio
  File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 40, in <module>
    from . import events
  File "/usr/local/lib/python3.10/asyncio/events.py", line 204, in <module>
    class AbstractEventLoop:
  File "/usr/local/lib/python3.10/asyncio/events.py", line 499, in AbstractEventLoop
    stdin=subprocess.PIPE,
AttributeError: partially initialized module 'subprocess' has no attribute 'PIPE' (most likely due to a circular import)
```
I guess I'm seeing this now and not earlier because of the fix with the logging module you did.

**Review by euri10 — APPROVED** [review]

**Comment by matgnt** [comment]
I saw the  failing test cases. I did only ./scripts/lint
Running ./scripts/check now and will push in a second...

**Comment by euri10** [comment]
can you run the lint script @matgnt please ?

**Review by euri10 — CHANGES_REQUESTED** [review]
can you run the lint script @matgnt please ?

**Comment by matgnt** [comment]
> can you run the lint script @matgnt please ?

Done.

**Review by euri10 — APPROVED** [review]

**Comment by euri10** [comment]
thanks @matgnt !

**Comment by Kludex** [comment]
This is a breaking change, jfyk

**Comment by Kludex** [comment]
Not sure if we should be doing this... 🤔

Instead we should plan the privatization of most of modules, instead of the ones that cause errors on misusage 🤔

**Comment by euri10** [comment]
I dont see why, this is not supposed to be public API anyways ?

**Comment by Kludex** [comment]
> I dont see why, this is not supposed to be public API anyways ?

Supposed... But it's public (considering that we don't have rules about it).

**Pull request merged**
