### PR TITLE
improve handling of transfer-encoding

### PR DESCRIPTION
**Pull request by mkiesel**
httptools_impl added a second transfer-encoding header
in case the app set transfer-encoding: gzip or similar
without giving a content length. Also, it used chunked
for responses to HTTP/1.0 requests (those clients do
not support chunked encoding). Finally, this adds a way
to force non-chunked transfer as there are quite a few
music streaming devices that issue HTTP/1.1 requests
but do not understand chunked encoding.

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Could you provide a link to give some more context here?

Nothing here: https://github.com/MagicStack/httptools/issues?q=just_stream
Or here: https://www.google.com/search?q=httptools+just_stream

**Comment by lovelydinosaur** [comment]
Going to close this off in the meantime, as we really need to start pushing for suggestions to come through discussions first.

**Comment by mkiesel** [comment]
Where/how am I to give more context? These problems are all Uvicorn related and have nothing to do with upstream httptools.

This PR includes four test cases, did you see those?
* **test_get_streaming_gzip_request** makes sure Uvicorn doesn't garble responses made by the app with Transfer-Encoding: gzip or similar. Currently, for those responses, it injects a second Transfer-Encoding: chunked header.
* **test_get_streaming_http10_request** makes sure Uvicorn doesn't reply with Transfer-Encoding: chunked for a HTTP/1.0 request. HTTP 1.0 clients don't support chunked encoding.
* **test_get_streaming_nochunked_request** checks the Transfer-Encoding: just_stream header handling. This is a bit of a hack to somehow allow the app to make sure Uvicorn just passes through any response stream data without "chunking" it; the code will not send that header to the client but rather treat it as a flag only. As explained above, some hardware streaming devices cannot process chunked encoding, but as it is,Uvicorn forces chunked encoding for all streams. If you have a better idea of how to implement this workaround, let me know.
* **test_get_streaming_http11_request** is the only test that passes on current Uvicorn as well; I just added that since there appeared to be no actual tests for that case in the existing tests.

I can also create a couple of issues if you think that's better than one PR.

**Comment by mkiesel** [comment]
Discussion see https://github.com/encode/uvicorn/discussions/2645

**Comment by lovelydinosaur** [comment]
It's not obvious to me that #2645 is correct - does it ensure connection closing?
It looks like the h11 implementation correctly supports this... https://h11.readthedocs.io/en/latest/api.html

**Comment by mkiesel** [comment]
Do you mean https://github.com/encode/uvicorn/pull/1360 ? https://github.com/encode/uvicorn/discussions/2645 is just a discussion.

I'm not sure the code in https://github.com/encode/uvicorn/pull/1360 (that also contains the `just_stream` hack that I need for my scenarios in which clients connect that say they can manage HTTP/1.1 but actually they don't support chunked encoding...) is 100% complete and correct, but I'm fairly sure that the issue raised in https://github.com/encode/uvicorn/discussions/2645 is correct. :)

**Pull request closed without merging**
