### PR TITLE
Add example how to run the server programmatically with reload

### PR DESCRIPTION
**Pull request by SergeyTsaplin**
Add an example of how to run the uvicorn with the reload option programmatically.

### CODE REVIEW

**Comment by SergeyTsaplin** [comment]
Anybody here?

**Comment by Kludex** [comment]
yes

**Comment by Kludex** [comment]
We'll check shortly. Thanks for the PR! 🙏

**Comment by Kludex** [comment]
Well... You just made me noticed that we have a "Running programmatically" section on both pages on our documentation.

image

🤦‍♂️

**Comment by SergeyTsaplin** [comment]
> Well... You just made me noticed that we have a "Running programmatically" section on both pages on our documentation.
> 
> 
> 
> image
> 
> 
So, should I add the same example to the second page?

**Comment by Kludex** [comment]
I'll think about this, and get back here. The documentation structure may need some small changes.

**Review by Kludex — APPROVED** [review]
Thank you @SergeyTsaplin ! :tada:

**Comment by Kludex** [comment]
I think I'm going to have to patch the docs before the release...

@SergeyTsaplin Why not the following?

```python
if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host="127.0.0.1",
        port=8000,
        log_level="info",
        reload=True,
    )
```

**Pull request merged**
