### PR TITLE
Upgraded black to avoid clash with newest click

### PR DESCRIPTION
**Pull request by euri10**
see https://github.com/psf/black/issues/2964

an example of our CI broken : https://github.com/encode/uvicorn/runs/5735122920?check_suite_focus=true

### CODE REVIEW

**Review by Kludex — DISMISSED** [review]

**Comment by euri10** [comment]
yup realized that too late :) updated

**Comment by euri10** [comment]
ok we got an issue click is 7.18 in CI so should be bunp it as well ?

**Comment by Kludex** [comment]
How is it `click` that old there? 🤔 Which package is holding it down?

**Comment by euri10** [comment]
> How is it `click` that old there? thinking Which package is holding it down?

my bad it's types-click which is on that version, ci on linux install 8.1 fine, it seems like it's windows specifics, again...

**Comment by euri10** [comment]
seems like windows ci install 8.0.4 and linux 8.1 so we're doomed

**Comment by Kludex** [comment]
Ah... Then we should run the cli tool only on linux... ?

**Comment by euri10** [comment]
> Ah... Then we should run the cli tool only on linux... ?

or drop windows support ! :imp:

**Comment by Kludex** [comment]
Replaced by #1428

**Pull request closed without merging**
