### PR TITLE
Allow app-dir parameter on the run() function

### LINKED ISSUE #1126: allow uvicorn.run to also accept app-dir kwarg
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [x] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

The issue is: I have a script using uvicorn.run, but I can only run it from a specific cwd, else it will fail with ImportError.

## Describe the solution you would like.

I would like the --app-dir functionality to be available in uvicorn.run() as well.
I.e.: to be able to run a script containing a call to uvicorn.run regardless of the cwd.

## Describe alternatives you considered

Doing it myself, i.e. calling sys.path.insert(0, abs_path_to_my_project_root_folder), but it feels to me that if this functionality is implemented in main() but not in run() (which from reading the code are the same thing) there must be something wrong with the uvicorn code.

## Additional context

https://github.com/encode/uvicorn/issues/549
https://github.com/encode/uvicorn/pull/619
https://github.com/encode/uvicorn/commit/77468df7697ec2f2962e77d7a02e0bc22b6f9c79

My guess is that this commit implemented the behaviour in the wrong place. Instead of 'consuming' the app_dir argument inside main(), it should have been passed down as-is to run() where it will be processed.

(I volunteer to do the job, if we agree that there is a problem)

### PR DESCRIPTION
**Pull request by Kludex**
Closes #1126

### CODE REVIEW

**Comment by Kludex** [comment]
@HansBrende You recommended the solution, so feel free to review as well. :pray:

**Review by HansBrende — APPROVED** [review]
LGTM!

**Comment by Kludex** [comment]
@euri10 ping

**Review by euri10 — APPROVED** [review]
I think this looks good, the only small thing that may make it better is adding a test, I realize original PR that introduced the feature doesn't have one either so we're naked here and this will hit when working again on coverage anyway.
So approved, but feel free to add tests ;)

**Comment by Kludex** [comment]
I will add, thanks. ✌️

**Comment by Kludex** [comment]
How would you test this?

I started with this thought:
```python
def test_app_dir(tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
    app_dir = tmp_path / "dir" / "app_dir"
    app_file = app_dir / "main.py"
    app_dir.mkdir(parents=True)
    app_file.touch()
    app_file.write_text(
        dedent(
            """
            async def app(scope, receive, send):
                ...
            """
        )
    )
    run("main:app", app_dir=str(app_dir))
```
But the server will run, and we don't want that. We use `run_server` in similar cases.

After that I thought: "we'll, let's mock the `server.run`. But if I do that, we'll not test that we reached the `import_string` successfully... 

Ideas?

**Comment by humrochagf** [comment]
Hi!

You can try to use the way I did for the cli tools https://github.com/encode/uvicorn/blob/master/tests/test_cli.py#L69-L78
Mock just the `Config.bind_socket` and `Server.run` to prevent the actual server from running and also from locking the socket.

Then you can check `sys.path` to validate the `app_dir` path was added to it

**Comment by Kludex** [comment]
I'm going to add the test suggested by @humrochagf (thanks).

But that's not fully what I want. I want to be able to know that `app` was imported. But to do that, I'll have to complicate things.

**Pull request merged**
