### PR TITLE
WIP: Watchdog duplicate log

### PR DESCRIPTION
**Pull request by euri10**
- [ ] find a working test

This fix the duplicate logs happening when modifying a file
It fails the test though and cant wrap my head around fixing the test.
I used one of the workarounds provided in what seems to be an upstream issue in [watchdog](https://github.com/gorakhargosh/watchdog/issues/93)

### CODE REVIEW

**Comment by euri10** [comment]
this is a debug log without it, seems like watchdog sends twice the same modified event,
```
INFO:     Started server process [14875]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
DEBUG:    in-event <InotifyEvent: src_path=b'/home/lotso/PycharmProjects/uvicorn/app.py~', wd=1, mask=IN_CREATE, cookie=0, name=app.py~>
DEBUG:    in-event <InotifyEvent: src_path=b'/home/lotso/PycharmProjects/uvicorn/app.py~', wd=1, mask=IN_MODIFY, cookie=0, name=app.py~>
DEBUG:    in-event <InotifyEvent: src_path=b'/home/lotso/PycharmProjects/uvicorn/app.py', wd=1, mask=IN_MODIFY, cookie=0, name=app.py>
INFO:     modified at: 1586502925.2758348
WARNING:  Detected file change in '/home/lotso/PycharmProjects/uvicorn/app.py'. Reloading...
DEBUG:    in-event <InotifyEvent: src_path=b'/home/lotso/PycharmProjects/uvicorn/app.py', wd=1, mask=IN_MODIFY, cookie=0, name=app.py>
DEBUG:    in-event <InotifyEvent: src_path=b'/home/lotso/PycharmProjects/uvicorn/app.py~', wd=1, mask=IN_DELETE, cookie=0, name=app.py~>
INFO:     modified at: 1586502925.2758348
WARNING:  Detected file change in '/home/lotso/PycharmProjects/uvicorn/app.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14875]
INFO:     email-validator not installed, email fields will be treated as str.

```

**Comment by euri10** [comment]
can be solved even more simply by using 
`from watchdog.observers import PollingObserver as Observer`

this said in that case why not using watchgod which defaults to file polling (https://github.com/samuelcolvin/watchgod#why-no-inotify--kqueue--fsevent--winapi-support

**Comment by euri10** [comment]
irrelevant after #624

**Comment by dss010101** [comment]
cannot import PollingObserver.   Is there ever gonna be a fix to this duplicate event issue

**Pull request closed without merging**
