### PR TITLE
test(signal): add sleep to ensure shutdown completion

### PR DESCRIPTION
**Pull request by vvanglro**
# Summary
#2382 

# Checklist

- [ ] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [ ] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by Kludex** [comment]
Is this about the hanging test?

**Comment by vvanglro** [comment]
> Is this about the hanging test?

No, is a patch to 2382. Increases stability of signal tests
https://github.com/encode/uvicorn/actions/runs/10365937979/job/28694114428

https://github.com/encode/uvicorn/actions/runs/10365916920/job/28694050767

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
Thanks 🙏

**Comment by vvanglro** [comment]
Later I will investigate why the test is hanging.

**Pull request merged**
