### PR TITLE
WIP: Implement h2 protocol

### PR DESCRIPTION
**Pull request by songww**
#47 

Something to be fixed:
1. Too much code is duplicated with H11's implementation.
2. `ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify`. This error occurred with hypercorn too.
3. `connection: upgrade` support. to websocket and h11 to h2(https auto upgrade to h2 is supported).
4. logger
5. tests

It works.

### CODE REVIEW

**Comment by lovelydinosaur** [comment]
Thanks so much for your work on this, sorry I’ve not been able to review yet. Any particular reason for the close?

**Comment by songww** [comment]
There are still many problems, but I don't have time to continue on it.

**Comment by lovelydinosaur** [comment]
Gotcha. Thanks for submitting all the same. Will get onto http/2 support in time, so this’ll be really helpful when we get there.

**Comment by ahopkins** [comment]
I'm one of the developers  on [sanic](https://github.com/huge-success/sanic). Adding HTTP2 has been on the [radar for sanic for a while](https://github.com/huge-success/sanic/pull/472).

@tomchristie submitted [this PR](https://github.com/huge-success/sanic/pull/1265) to add an ASGI interface. Thanks Tom!

Just curious what the plan is for uvicorn and what the current hurdles are to get http2 implemented.

**Comment by lovelydinosaur** [comment]
@ahopkins - There's no significant technical hurdles, just time.

The Hypercorn and Daphne ASGI servers already supports HTTP/2, so we have alternative implementations. Presumably we'll add one for Uvicorn based on a similar implementation.

**Comment by ahopkins** [comment]
@tomchristie Got it. Thanks. :+1: 

Might I suggest:

```
from time import more

more.make(hours=6)
```

**Pull request closed without merging**
